# fly.toml app configuration file generated for backenddogs on 2023-11-02T21:31:28-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backenddogs"
primary_region = "bos"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
